/**
 * vehicle-classifier — native module interface
 *
 * iOS:  CoreML (Neural Engine accelerated)
 * Android: TFLite (GPU delegate on Snapdragon 778G+)
 *
 * The real implementation lives in the native module (ios/ and android/
 * directories generated by expo prebuild). This file exports the JS
 * interface that screens import.
 *
 * For dev without native modules, swap to VehicleClassifierStub below.
 */

import { requireOptionalNativeModule } from 'expo-modules-core';

export type ClassifyResult = {
  make: string;
  model: string;
  generation: string;
  bodyStyle: string;
  color: string;
  confidence: number;               // 0.0 – 1.0
  boundingBox: { x: number; y: number; width: number; height: number };
};

export interface IVehicleClassifier {
  /** Full ResNet50V2 CoreML classification from a snapshot file path. */
  classify(imagePath: string): Promise<ClassifyResult | null>;

  /** Version string of the loaded model, or 'stub-0.0.1' when running the stub. */
  modelVersion(): string;
}

const NativeClassifier = requireOptionalNativeModule<IVehicleClassifier>('VehicleClassifier');
export const VehicleClassifier = NativeClassifier as IVehicleClassifier;

// ---------------------------------------------------------------------------
// Stub — use in Expo Go / dev builds without native modules
//
// Draws from the real vehicle catalog with volume-weighted probability so
// test catches reflect the actual rarity distribution in the game.
// Safe to call from Reanimated worklets (no async, no imports).
// ---------------------------------------------------------------------------

type StubVehicle = {
  make: string; model: string; generation: string;
  bodyStyle: string; rarity: string; weight: number;
};

// Sourced directly from seed_vehicles.py — weight = annual_volume / 1000
const STUB_CATALOG: StubVehicle[] = [
  // ── Common ────────────────────────────────────────────────────────────────
  { make: 'Toyota',       model: 'Camry',            generation: 'XV70 (2018–present)',       bodyStyle: 'Sedan',   rarity: 'common',    weight: 336 },
  { make: 'Toyota',       model: 'Corolla',           generation: 'E210 (2019–present)',       bodyStyle: 'Sedan',   rarity: 'common',    weight: 300 },
  { make: 'Toyota',       model: 'RAV4',              generation: 'XA50 (2019–present)',       bodyStyle: 'SUV',     rarity: 'common',    weight: 430 },
  { make: 'Toyota',       model: 'Tacoma',            generation: '3rd Gen (2016–present)',    bodyStyle: 'Truck',   rarity: 'common',    weight: 270 },
  { make: 'Toyota',       model: 'Highlander',        generation: 'XU70 (2020–present)',       bodyStyle: 'SUV',     rarity: 'common',    weight: 240 },
  { make: 'Toyota',       model: 'Tundra',            generation: '3rd Gen (2022–present)',    bodyStyle: 'Truck',   rarity: 'common',    weight: 100 },
  { make: 'Toyota',       model: 'Prius',             generation: 'XW50 (2016–2022)',          bodyStyle: 'Hatchback', rarity: 'common',  weight: 100 },
  { make: 'Honda',        model: 'Civic',             generation: '11th Gen (2022–present)',   bodyStyle: 'Sedan',   rarity: 'common',    weight: 310 },
  { make: 'Honda',        model: 'Accord',            generation: '10th Gen (2018–2022)',      bodyStyle: 'Sedan',   rarity: 'common',    weight: 220 },
  { make: 'Honda',        model: 'CR-V',              generation: '5th Gen (2017–2022)',       bodyStyle: 'SUV',     rarity: 'common',    weight: 400 },
  { make: 'Ford',         model: 'F-150',             generation: 'P702 (2021–present)',       bodyStyle: 'Truck',   rarity: 'common',    weight: 650 },
  { make: 'Ford',         model: 'Explorer',          generation: '6th Gen (2020–present)',    bodyStyle: 'SUV',     rarity: 'common',    weight: 230 },
  { make: 'Ford',         model: 'Escape',            generation: '4th Gen (2020–present)',    bodyStyle: 'SUV',     rarity: 'common',    weight: 200 },
  { make: 'Chevrolet',    model: 'Silverado 1500',    generation: 'T1 (2019–present)',         bodyStyle: 'Truck',   rarity: 'common',    weight: 500 },
  { make: 'Chevrolet',    model: 'Equinox',           generation: '3rd Gen (2018–present)',    bodyStyle: 'SUV',     rarity: 'common',    weight: 300 },
  { make: 'Chevrolet',    model: 'Tahoe',             generation: '5th Gen (2021–present)',    bodyStyle: 'SUV',     rarity: 'common',    weight: 100 },
  { make: 'Chevrolet',    model: 'Malibu',            generation: '9th Gen (2016–2024)',       bodyStyle: 'Sedan',   rarity: 'common',    weight: 180 },
  { make: 'Ram',          model: '1500',              generation: 'DT (2019–present)',         bodyStyle: 'Truck',   rarity: 'common',    weight: 400 },
  { make: 'GMC',          model: 'Sierra 1500',       generation: 'T1 (2019–present)',         bodyStyle: 'Truck',   rarity: 'common',    weight: 200 },
  { make: 'GMC',          model: 'Yukon',             generation: '5th Gen (2021–present)',    bodyStyle: 'SUV',     rarity: 'common',    weight: 80  },
  { make: 'Jeep',         model: 'Grand Cherokee',    generation: 'WL (2021–present)',         bodyStyle: 'SUV',     rarity: 'common',    weight: 170 },
  { make: 'Jeep',         model: 'Wrangler',          generation: 'JK (2007–2017)',            bodyStyle: 'SUV',     rarity: 'common',    weight: 180 },
  { make: 'Nissan',       model: 'Rogue',             generation: '3rd Gen (2021–present)',    bodyStyle: 'SUV',     rarity: 'common',    weight: 350 },
  { make: 'Nissan',       model: 'Altima',            generation: '6th Gen (2019–present)',    bodyStyle: 'Sedan',   rarity: 'common',    weight: 200 },
  { make: 'Hyundai',      model: 'Tucson',            generation: 'NX4 (2022–present)',        bodyStyle: 'SUV',     rarity: 'common',    weight: 250 },
  { make: 'Hyundai',      model: 'Elantra',           generation: 'CN7 (2021–present)',        bodyStyle: 'Sedan',   rarity: 'common',    weight: 200 },
  { make: 'Hyundai',      model: 'Sonata',            generation: 'DN8 (2020–present)',        bodyStyle: 'Sedan',   rarity: 'common',    weight: 200 },
  { make: 'Kia',          model: 'Sportage',          generation: 'NQ5 (2023–present)',        bodyStyle: 'SUV',     rarity: 'common',    weight: 200 },
  { make: 'Kia',          model: 'K5',                generation: 'DL3 (2021–present)',        bodyStyle: 'Sedan',   rarity: 'common',    weight: 100 },
  { make: 'Mazda',        model: 'CX-5',              generation: 'KF (2017–present)',         bodyStyle: 'SUV',     rarity: 'common',    weight: 300 },
  { make: 'Mazda',        model: 'Mazda3',            generation: 'BP (2019–present)',         bodyStyle: 'Sedan',   rarity: 'common',    weight: 100 },
  { make: 'Subaru',       model: 'Outback',           generation: '6th Gen (2020–present)',    bodyStyle: 'Wagon',   rarity: 'common',    weight: 100 },
  { make: 'Subaru',       model: 'Forester',          generation: 'SK (2019–present)',         bodyStyle: 'SUV',     rarity: 'common',    weight: 80  },
  { make: 'Volkswagen',   model: 'Jetta',             generation: '7th Gen (2019–present)',    bodyStyle: 'Sedan',   rarity: 'common',    weight: 100 },
  { make: 'Volkswagen',   model: 'Tiguan',            generation: '2nd Gen (2018–present)',    bodyStyle: 'SUV',     rarity: 'common',    weight: 90  },
  // ── Uncommon ──────────────────────────────────────────────────────────────
  { make: 'Toyota',       model: '4Runner',           generation: 'N280 (2010–present)',       bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 90  },
  { make: 'Toyota',       model: 'Prius',             generation: 'XW60 (2023–present)',       bodyStyle: 'Hatchback', rarity: 'uncommon', weight: 80 },
  { make: 'Honda',        model: 'Pilot',             generation: '4th Gen (2023–present)',    bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 100 },
  { make: 'Honda',        model: 'Ridgeline',         generation: '2nd Gen (2017–present)',    bodyStyle: 'Truck',   rarity: 'uncommon',  weight: 80  },
  { make: 'Ford',         model: 'Bronco',            generation: '7th Gen (2021–present)',    bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 90  },
  { make: 'Ford',         model: 'Maverick',          generation: '1st Gen (2022–present)',    bodyStyle: 'Truck',   rarity: 'uncommon',  weight: 80  },
  { make: 'Jeep',         model: 'Wrangler',          generation: 'JL (2018–present)',         bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 55  },
  { make: 'Jeep',         model: 'Gladiator',         generation: 'JT (2020–present)',         bodyStyle: 'Truck',   rarity: 'uncommon',  weight: 60  },
  { make: 'BMW',          model: '3 Series',          generation: 'G20 (2019–present)',        bodyStyle: 'Sedan',   rarity: 'uncommon',  weight: 120 },
  { make: 'BMW',          model: '5 Series',          generation: 'G30 (2017–2023)',           bodyStyle: 'Sedan',   rarity: 'uncommon',  weight: 90  },
  { make: 'BMW',          model: 'X3',                generation: 'G01 (2018–present)',        bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 100 },
  { make: 'BMW',          model: 'X5',                generation: 'G05 (2019–present)',        bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 90  },
  { make: 'Mercedes-Benz', model: 'C-Class',          generation: 'W205 (2015–2021)',          bodyStyle: 'Sedan',   rarity: 'uncommon',  weight: 120 },
  { make: 'Mercedes-Benz', model: 'E-Class',          generation: 'W213 (2017–2023)',          bodyStyle: 'Sedan',   rarity: 'uncommon',  weight: 80  },
  { make: 'Mercedes-Benz', model: 'GLE',              generation: 'W167 (2020–present)',       bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 90  },
  { make: 'Audi',         model: 'A4',                generation: 'B9 (2017–present)',         bodyStyle: 'Sedan',   rarity: 'uncommon',  weight: 80  },
  { make: 'Audi',         model: 'Q5',                generation: 'FY (2018–present)',         bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 110 },
  { make: 'Tesla',        model: 'Model 3',           generation: 'Gen 1 (2017–2023)',         bodyStyle: 'Sedan',   rarity: 'uncommon',  weight: 180 },
  { make: 'Tesla',        model: 'Model Y',           generation: 'Gen 1 (2020–2024)',         bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 600 },
  { make: 'Lexus',        model: 'RX',                generation: 'AL20 (2016–2022)',          bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 100 },
  { make: 'Lexus',        model: 'IS',                generation: 'XE30 (2014–present)',       bodyStyle: 'Sedan',   rarity: 'uncommon',  weight: 40  },
  { make: 'Infiniti',     model: 'Q50',               generation: 'V37 (2014–present)',        bodyStyle: 'Sedan',   rarity: 'uncommon',  weight: 40  },
  { make: 'Acura',        model: 'RDX',               generation: '3rd Gen (2019–present)',    bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 70  },
  { make: 'Acura',        model: 'MDX',               generation: '4th Gen (2022–present)',    bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 50  },
  { make: 'Kia',          model: 'Telluride',         generation: 'ON (2020–present)',         bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 100 },
  { make: 'Hyundai',      model: 'Ioniq 5',           generation: 'NE1 (2022–present)',        bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 60  },
  { make: 'Genesis',      model: 'GV80',              generation: 'JX1 (2021–present)',        bodyStyle: 'SUV',     rarity: 'uncommon',  weight: 15  },
  { make: 'Dodge',        model: 'Challenger',        generation: 'LC (2008–2023)',            bodyStyle: 'Coupe',   rarity: 'uncommon',  weight: 70  },
  { make: 'Dodge',        model: 'Charger',           generation: 'LD (2011–2023)',            bodyStyle: 'Sedan',   rarity: 'uncommon',  weight: 100 },
  { make: 'Nissan',       model: 'Z',                 generation: 'Z34 (2009–2020)',           bodyStyle: 'Coupe',   rarity: 'uncommon',  weight: 12  },
  // ── Rare ──────────────────────────────────────────────────────────────────
  { make: 'Toyota',       model: 'GR86',              generation: 'ZN8 (2022–present)',        bodyStyle: 'Coupe',   rarity: 'rare',      weight: 15  },
  { make: 'Toyota',       model: 'GR86',              generation: 'ZN6 (2012–2021)',           bodyStyle: 'Coupe',   rarity: 'rare',      weight: 12  },
  { make: 'Ford',         model: 'Mustang',           generation: '7th Gen (2024–present)',    bodyStyle: 'Coupe',   rarity: 'rare',      weight: 50  },
  { make: 'Subaru',       model: 'WRX',               generation: 'VB (2022–present)',         bodyStyle: 'Sedan',   rarity: 'rare',      weight: 15  },
  { make: 'Subaru',       model: 'BRZ',               generation: 'ZD8 (2022–present)',        bodyStyle: 'Coupe',   rarity: 'rare',      weight: 8   },
  { make: 'Volkswagen',   model: 'Golf GTI',          generation: 'Mk8 (2022–present)',        bodyStyle: 'Hatchback', rarity: 'rare',    weight: 25  },
  { make: 'Mazda',        model: 'MX-5 Miata',        generation: 'ND (2016–present)',         bodyStyle: 'Convertible', rarity: 'rare',  weight: 10  },
  { make: 'Kia',          model: 'Stinger',           generation: 'CK (2018–2023)',            bodyStyle: 'Sedan',   rarity: 'rare',      weight: 15  },
  { make: 'Acura',        model: 'Integra',           generation: '5th Gen (2023–present)',    bodyStyle: 'Hatchback', rarity: 'rare',    weight: 12  },
  { make: 'Porsche',      model: 'Cayenne',           generation: 'PO536 (2018–present)',      bodyStyle: 'SUV',     rarity: 'rare',      weight: 40  },
  { make: 'Porsche',      model: 'Taycan',            generation: 'J1 (2020–present)',         bodyStyle: 'Sedan',   rarity: 'rare',      weight: 20  },
  { make: 'Tesla',        model: 'Model S',           generation: 'Plaid Era (2021–present)',  bodyStyle: 'Sedan',   rarity: 'rare',      weight: 35  },
  { make: 'Tesla',        model: 'Cybertruck',        generation: 'Gen 1 (2024–present)',      bodyStyle: 'Truck',   rarity: 'rare',      weight: 25  },
  { make: 'Genesis',      model: 'G70',               generation: 'IK (2019–present)',         bodyStyle: 'Sedan',   rarity: 'rare',      weight: 8   },
  { make: 'Nissan',       model: 'Z',                 generation: 'RZ34 (2023–present)',       bodyStyle: 'Coupe',   rarity: 'rare',      weight: 8   },
  { make: 'Chevrolet',    model: 'Corvette',          generation: 'C7 (2014–2019)',            bodyStyle: 'Coupe',   rarity: 'rare',      weight: 30  },
  { make: 'Cadillac',     model: 'Escalade',          generation: '5th Gen (2021–present)',    bodyStyle: 'SUV',     rarity: 'rare',      weight: 30  },
  // ── Epic ──────────────────────────────────────────────────────────────────
  { make: 'Toyota',       model: 'Supra',             generation: 'A90 (2019–present)',        bodyStyle: 'Coupe',   rarity: 'epic',      weight: 10  },
  { make: 'Honda',        model: 'Civic Type R',      generation: 'FL5 (2022–present)',        bodyStyle: 'Hatchback', rarity: 'epic',    weight: 10  },
  { make: 'BMW',          model: 'M3',                generation: 'G80 (2021–present)',        bodyStyle: 'Sedan',   rarity: 'epic',      weight: 10  },
  { make: 'BMW',          model: 'M4',                generation: 'G82 (2021–present)',        bodyStyle: 'Coupe',   rarity: 'epic',      weight: 8   },
  { make: 'Mercedes-Benz', model: 'G-Class',          generation: 'W463A (2019–present)',      bodyStyle: 'SUV',     rarity: 'epic',      weight: 12  },
  { make: 'Mercedes-Benz', model: 'AMG GT',           generation: 'C192 (2023–present)',       bodyStyle: 'Coupe',   rarity: 'epic',      weight: 3   },
  { make: 'Audi',         model: 'RS3',               generation: '8Y (2022–present)',         bodyStyle: 'Sedan',   rarity: 'epic',      weight: 5   },
  { make: 'Volkswagen',   model: 'Golf R',            generation: 'Mk8R (2022–present)',       bodyStyle: 'Hatchback', rarity: 'epic',    weight: 10  },
  { make: 'Porsche',      model: '911',               generation: '992 (2019–present)',        bodyStyle: 'Coupe',   rarity: 'epic',      weight: 30  },
  { make: 'Chevrolet',    model: 'Corvette',          generation: 'C8 (2020–present)',         bodyStyle: 'Coupe',   rarity: 'epic',      weight: 35  },
  { make: 'Cadillac',     model: 'CT5-V Blackwing',   generation: '2022–present',              bodyStyle: 'Sedan',   rarity: 'epic',      weight: 2   },
  { make: 'Lamborghini',  model: 'Urus',              generation: '1st Gen (2018–present)',    bodyStyle: 'SUV',     rarity: 'epic',      weight: 4   },
  { make: 'Lexus',        model: 'LC 500',            generation: 'Z100 (2017–present)',       bodyStyle: 'Coupe',   rarity: 'epic',      weight: 3   },
  // ── Legendary ─────────────────────────────────────────────────────────────
  { make: 'Nissan',       model: 'GT-R',              generation: 'R35 (2007–present)',        bodyStyle: 'Coupe',   rarity: 'legendary', weight: 2   },
  { make: 'Audi',         model: 'R8',                generation: 'Type 4S (2016–present)',    bodyStyle: 'Coupe',   rarity: 'legendary', weight: 2   },
  { make: 'Lamborghini',  model: 'Huracán',           generation: 'LP 580/610 (2014–present)', bodyStyle: 'Coupe',  rarity: 'legendary', weight: 3   },
  { make: 'Ferrari',      model: 'Roma',              generation: 'F169 (2020–present)',       bodyStyle: 'Coupe',   rarity: 'legendary', weight: 2   },
  { make: 'Ferrari',      model: 'SF90 Stradale',     generation: 'F173 (2021–present)',       bodyStyle: 'Coupe',   rarity: 'legendary', weight: 1   },
  { make: 'McLaren',      model: '720S',              generation: 'P14 (2017–present)',        bodyStyle: 'Coupe',   rarity: 'legendary', weight: 1   },
  { make: 'McLaren',      model: 'Artura',            generation: 'MC30 (2022–present)',       bodyStyle: 'Coupe',   rarity: 'legendary', weight: 1   },
  { make: 'Acura',        model: 'NSX',               generation: 'NC1 (2016–2022)',           bodyStyle: 'Coupe',   rarity: 'legendary', weight: 1   },
  { make: 'Porsche',      model: '911',               generation: '991 (2012–2019)',           bodyStyle: 'Coupe',   rarity: 'legendary', weight: 1   },
];

const COLORS = [
  'Midnight Black', 'Pearl White', 'Slate Gray', 'Silver Metallic',
  'Sonic Red', 'Deep Blue', 'Forest Green', 'Burnt Orange',
  'Championship White', 'Matte Gray', 'Champagne Gold', 'Icy Blue',
  'Racing Yellow', 'Volcanic Orange', 'Frozen White', 'Storm Blue',
];

// Precompute cumulative weights for O(log n) weighted random selection
const _TOTAL_WEIGHT = STUB_CATALOG.reduce((s, v) => s + v.weight, 0);
const _CUMULATIVE   = STUB_CATALOG.map((() => {
  let acc = 0;
  return (v: StubVehicle) => { acc += v.weight; return acc; };
})());

function weightedRandom(): StubVehicle {
  const r = Math.random() * _TOTAL_WEIGHT;
  // Binary search for the bucket
  let lo = 0, hi = _CUMULATIVE.length - 1;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (_CUMULATIVE[mid] < r) lo = mid + 1;
    else hi = mid;
  }
  return STUB_CATALOG[lo];
}

export const VehicleClassifierStub: IVehicleClassifier = {
  async classify(_imagePath) {
    if (Math.random() < 0.1) return null;  // ~10% miss rate

    const v          = weightedRandom();
    const confidence = 0.55 + Math.random() * 0.44;
    const color      = COLORS[Math.floor(Math.random() * COLORS.length)];

    return {
      make:        v.make,
      model:       v.model,
      generation:  v.generation,
      bodyStyle:   v.bodyStyle,
      color,
      confidence,
      boundingBox: { x: 0.1, y: 0.2, width: 0.6, height: 0.5 },
    };
  },

  modelVersion() { return 'stub-0.0.1'; },
};
