/**
 * vehicle-classifier — native module interface
 *
 * iOS:  CoreML (Neural Engine accelerated)
 * Android: TFLite (GPU delegate on Snapdragon 778G+)
 *
 * The real implementation lives in the native module (ios/ and android/
 * directories generated by expo prebuild). This file exports the JS
 * interface that screens import.
 *
 * For dev without native modules, swap to VehicleClassifierStub below.
 */

import { NativeModules } from 'react-native';

const { VehicleClassifierModule } = NativeModules;

export type ClassifyResult = {
  make: string;
  model: string;
  generation: string;
  bodyStyle: string;
  color: string;
  confidence: number;               // 0.0 – 1.0
  boundingBox: { x: number; y: number; width: number; height: number };
};

export interface IVehicleClassifier {
  /**
   * Stage 1 — lightweight MobileNet SSD trigger.
   * Runs at 2fps. Returns true if a vehicle superclass is detected.
   * Adaptive throttle: caller skips Stage 2 when false (AA pattern).
   */
  triggerDetect(frame: unknown): boolean;

  /**
   * Stage 2 — full EfficientNet-Lite B2 classification.
   * Called only when triggerDetect returns true.
   * Target: < 60ms on iPhone XS / Snapdragon 778G.
   */
  classify(frame: unknown): ClassifyResult | null;

  /**
   * Load a new model from the app documents directory (OTA update).
   * Returns true if the swap succeeded without restart.
   */
  loadModel(path: string): Promise<boolean>;

  /** Current loaded model version string */
  modelVersion(): string;
}

export const VehicleClassifier: IVehicleClassifier = VehicleClassifierModule;

// ---------------------------------------------------------------------------
// Stub — use in Expo Go / dev builds without native modules
// ---------------------------------------------------------------------------

export const VehicleClassifierStub: IVehicleClassifier = {
  triggerDetect(_frame) {
    // Simulate ~30% trigger rate
    return Math.random() < 0.3;
  },

  classify(_frame) {
    if (Math.random() < 0.1) return null;   // simulate miss

    const confidence = 0.55 + Math.random() * 0.44;
    return {
      make:        'Toyota',
      model:       'GR86',
      generation:  'ZN8 (2022–present)',
      bodyStyle:   'Coupe',
      color:       'Iced Coffee Brown',
      confidence,
      boundingBox: { x: 0.1, y: 0.2, width: 0.6, height: 0.5 },
    };
  },

  async loadModel(_path) { return true; },

  modelVersion() { return 'stub-0.0.1'; },
};
